version: "3"

services:
  app:
    container_name: blackglass_app
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo/blackglass
    depends_on:
      - mongodb
    networks:
      - prodnet

  mongodb:
    image: "mongo:latest"
    container_name: blackglass_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      prodnet:
        aliases:
          - "mongo"

networks:
  prodnet:
    driver: bridge
